---
language: python
python:
- '2.7'
install:
- 'pip install yamllint==1.13.0'
- 'pip install cfn-lint==0.10.1'
script:
- 'yamllint examples/'
- 'find examples -type f -name ''*.yml'' -not -name .eslintrc.yml | while read file; do set -ex && cfn-lint -t "$file"; done;'
- 'find examples -type f -name ''*.yml'' -not -name .eslintrc.yml | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;'
